apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-api
          image: nginx:alpine
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: non-existent-secret
                  key: password
          ports:
            - containerPort: 8080
